export enum ENVEnum {
  NODE_ENV = 'NODE_ENV',
  DATABASE_URL = 'DATABASE_URL',

  PORT = 'PORT',
  BASE_URL = 'BASE_URL',

  JWT_SECRET = 'JWT_SECRET',
  JWT_EXPIRES_IN = 'JWT_EXPIRES_IN',

  MAIL_USER = 'MAIL_USER',
  MAIL_PASS = 'MAIL_PASS',

  REDIS_HOST = 'REDIS_HOST',
  REDIS_PORT = 'REDIS_PORT',
  REDIS_USERNAME = 'REDIS_USERNAME',
  REDIS_PASSWORD = 'REDIS_PASSWORD',

  SUPER_ADMIN_EMAIL = 'SUPER_ADMIN_EMAIL',
  SUPER_ADMIN_PASS = 'SUPER_ADMIN_PASS',

  STRIPE_SECRET_KEY = 'STRIPE_SECRET_KEY',
  STRIPE_WEBHOOK_SECRET = 'STRIPE_WEBHOOK_SECRET',

  OAUTH_GMAIL_USER = 'OAUTH_GMAIL_USER',
  OAUTH_CLIENT_ID = 'OAUTH_CLIENT_ID',
  OAUTH_CLIENT_SECRET = 'OAUTH_CLIENT_SECRET',
  OAUTH_REFRESH_TOKEN = 'OAUTH_REFRESH_TOKEN',
}
